apiVersion: v1
kind: Service
metadata:
  labels:
    name: influxdb
  name: influxdb
spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
      port: 8086
      targetPort: 8086
      NodePort: 8086
