apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
    spec:
      containers:
      - image: phpmyadmin_alpine
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5050
          name: phpmyadmin
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'ps aux | egrep [t]elegraf'
          initialDelaySeconds: 10
          periodSeconds: 5
