apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps
    targetPort: 21
  - port: 21000
    name: ftps-data
    targetPort: 21000
  selector:
    app: ftps
