apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: NodePort
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
    nodePort: 21
  - name: ftps-data
    port: 21000
    targetPort: 21000
    nodePort: 21000
