apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/address-pool: ftps-ip
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 31000
    targetPort: 31000
    name: ftps-data
  selector:
    app: ftps
