apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: phpmyadmin
    tier: frontend
