apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/address-pool: wordpress_ip
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    name: http
  selector:
    app: wordpress
