apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_alpine
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'ps aux | egrep [t]elegraf'
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - mountPath: /ftp/user
          name: ftps-volume
        ports:
        - containerPort: 21
        - containerPort: 31000
      volumes:
      - name: ftps-volume
        hostPath:
          path: /data
          type: DirectoryOrCreate
