apiVersion: 1
datasources:
- name: InfluxDB
  type: influxdb
  url: http://influxdb.default:8086
  access: proxy
  isDefault: true
  user: root
  secureJsonData.password: password
  database: influxdb
